# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ifovWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QApplication
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.eflSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.eflSpinBox.setGeometry(QtCore.QRect(70, 80, 141, 28))
        self.eflSpinBox.setMaximum(100000.0)
        self.eflSpinBox.setProperty("value", 500.0)
        self.eflSpinBox.setObjectName("eflSpinBox")
        self.pitchSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.pitchSpinBox.setGeometry(QtCore.QRect(250, 80, 91, 28))
        self.pitchSpinBox.setProperty("value", 5.0)
        self.pitchSpinBox.setObjectName("pitchSpinBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(100, 170, 131, 28))
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.setProperty("value", 50)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 60, 76, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 60, 91, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 150, 91, 19))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.eflSpinBox.setSuffix(_translate("Form", "mm"))
        self.pitchSpinBox.setSuffix(_translate("Form", "um"))
        self.doubleSpinBox.setSuffix(_translate("Form", "urad"))
        self.label.setText(_translate("Form", "EFL"))
        self.label_2.setText(_translate("Form", "Pixel Pitch"))
        self.label_3.setText(_translate("Form", "IFOV"))


class IFOVApp(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self, parent=None):
        super(IFOVApp, self).__init__(parent)
        self.setupUi(self)


class IFOVCtrl():
    """PyCalc Controller class."""

    def __init__(self, view):
        """Controller initializer."""
        self._view = view
        # Connect signals and slots
        self._view.pitchSpinBox.valueChanged.connect(self.calc_ifov)
        self._view.eflSpinBox.valueChanged.connect(self.calc_ifov)

    def calc_ifov(self):
        """Calculates the instantaneous field of view and sends result to the doubleSpinBox"""
        pix_pitch = self._view.pitchSpinBox.value()
        efl = self._view.eflSpinBox.value()
        ifov = (pix_pitch / 1000) / efl  # in rad
        self._view.doubleSpinBox.setValue(ifov * 1e6)  #in urad


def mainApp():

    app = QApplication(sys.argv)
    view = IFOVApp()
    view.show()
    appCtrl = IFOVCtrl(view=view)
    # import pdb; pdb.set_trace()
    sys.exit(app.exec_())


if __name__ == '__main__':
    mainApp()
